## Config, just as the title says

name: "Digital and Multiplatform Storytelling"
description: "A weblog for 57999 Digital and Multiplatform Storytelling at UTS by Clara Tse"
language: en-AU
markdown: rdiscount
paginate: 4
baseurl: http://station.claratse.com

permalink: /:title/
timezone: Australia/Sydney
assets: http://dl.dropboxusercontent.com/u/158866275/station

author:
  name: Clara Tse
  url: http://kirinyan.net
  twitter: hanezawakirika
  github: ctse